
services:
  # 1. DATABASE
  postgres:
    image: postgres:15-alpine
    container_name: mb-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123123123
      - POSTGRES_DB=movie_booking_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mb-network

  # 2. MESSAGE BROKER
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: mb-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - mb-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: mb-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - mb-network

  # 3. KAFKA UI
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: mb-kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    networks:
      - mb-network

  # 4. REDIS
  redis:
    image: redis:alpine
    container_name: mb-redis
    ports:
      - "6379:6379"
    networks:
      - mb-network

networks:
  mb-network:
    driver: bridge

volumes:
  postgres_data: